/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppScreeningRouteImport } from './routes/_app/screening'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppJobsRouteImport } from './routes/_app/jobs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCandidatesRouteImport } from './routes/_app/candidates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScreeningRoute = AppScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/pipeline': typeof AppPipelineRoute
  '/screening': typeof AppScreeningRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidates': typeof AppCandidatesRoute
  '/dashboard': typeof AppDashboardRoute
  '/jobs': typeof AppJobsRoute
  '/pipeline': typeof AppPipelineRoute
  '/screening': typeof AppScreeningRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/candidates': typeof AppCandidatesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/jobs': typeof AppJobsRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/screening': typeof AppScreeningRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/pipeline'
    | '/screening'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidates'
    | '/dashboard'
    | '/jobs'
    | '/pipeline'
    | '/screening'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/candidates'
    | '/_app/dashboard'
    | '/_app/jobs'
    | '/_app/pipeline'
    | '/_app/screening'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/screening': {
      id: '/_app/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof AppScreeningRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs': {
      id: '/_app/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/candidates': {
      id: '/_app/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppJobsRoute: typeof AppJobsRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppScreeningRoute: typeof AppScreeningRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidatesRoute: AppCandidatesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppJobsRoute: AppJobsRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppScreeningRoute: AppScreeningRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
